spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/leaf?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  sql:
    init:
      mode: always
      platform: local

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #social
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 33639085746-931tb5adt8panu5jmgqqvvkfcen3vj12.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: 'http://localhost:8080/login/oauth2/code/google'
            authorization-grant-type: authorization_code
            scope: email, profile

          naver:
            client-id: kywqO7CA0wq7EL3fmr9P
            client-secret: XVVn1U5fCZ
            redirect-uri: 'http://localhost:8080/login/oauth2/code/naver'
            authorization-grant-type: authorization_code
            scope: name, account_email, birthday, birthyear, mobile

          kakao:
            client-id: 3c03055df153324beeade3cecb61260b
            redirect-uri: 'http://localhost:8080/login/oauth2/code/kakao'
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email, name, birthday, birthyear, phone_number

        provider:
          naver:
            authorization_uri: 'https://nid.naver.com/oauth2.0/authorize'
            token_uri: 'https://nid.naver.com/oauth2.0/token'
            user-info-uri: 'https://openapi.naver.com/v1/nid/me'
            user_name_attribute: response

          kakao:
            authorization_uri: 'https://kauth.kakao.com/oauth/authorize'
            token_uri: 'https://kauth.kakao.com/oauth/token'
            user-info-uri: 'https://kapi.kakao.com/v2/user/me'
            user_name_attribute: id
  data:
    redis:
      host: localhost
      port: 6379



jwt:
  secret: 4h2h24h2424h4g45yh436juh536j45hj246h4thtgdfh564h35g35hdrt6jr6j

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
